### ISSUE TITLE
Thank you and some ideas!

### ISSUE THREAD

**Issue by whichy** [debkbanerji/lego-art-remix#1]
We've been working on a mosaic project this week and found your site SUPER helpful.  So first of all we wanted to say thanks! It works great as is! But if you are planning on any future updates, we had a few quality of life suggestions:

1. Have the ability to save a custom color palate, that way it could be reloaded for a future project.  
2. Have an option to load the full set of currently available 1x1 round colors as a palate option.
3. The ability to name colors or have the standard color names come in from the above list and then print on the 1st page key.
4. Have a larger set of pixel frames available - we are doing a 3x(48x48) panel. So we did ours as 3 sets of instructions for each 48x48 panel.

[https://photos.app.goo.gl/iTDCYAci8WhrsfRx5](url) This is how far we got this morning.  

Also do you have a paypal/kofi/tipjar thing, we'd be happy to throw a bit your way. We were doing this manually with way less good results before we found your tool!.

**Comment by debkbanerji** [comment]
Thanks! I've broken down the feedback into individual issues, and I'll get to them at some point (feel free to leave comments on which ones would be more useful). Some are simpler than others, so I might start there. I'm closing this issue since I've opened others to track the feature requests.

The picture, it looks really nice - I wasn't able to find many test images with results that good, and I'm surprised how quickly it was built!

As for the tipjar question, I definitely don't need any money for this lol.

**Comment by debkbanerji** [comment]
Note: some of these issues have now been closed
