### ISSUE TITLE
Great tool!  Feature requests?

### ISSUE THREAD

**Issue by sdevine** [debkbanerji/lego-art-remix#10]
I saw this tool referenced on Brothers-Brick.com -- https://www.brothers-brick.com/2020/08/24/idea-to-actual-how-we-made-some-wonder-woman-lego-art-feature/   and had to try it out.  

Amazing tool!  I am not currently a mosaic maker, but I think this has me inspired.  

I had some ideas for features to add to expand this tool past the Lego Art sets:

- [x] Step 3 - Means to add multiple copies of the Lego Art sets to the counts 
- [x] Step 4 - Allow for 1x1 plates (part 3024) as an option
- [x] Step 4 - Allow for 1x1 tiles (part 3070b) as an option
- [x] Step 4 - Allow for 1x1 bricks (part 3005) as an option
- [x] Step 3 - Show the color name, either in a column or on hover
- [x] Step 4- For the PDF output, include a cover page of the rendered drawing.  
- [x] Step 3 - Allow adding of retired colors (https://www.bricklink.com/catalogColors.asp)
- [x] Step 3 - Indicate the counts needed for each color.  
- [x] Step 4 - For the PDF output, filename input field
- [x] Step 4 - For the PDF output, include color name on pages (or at least page 1)

**Comment by debkbanerji** [comment]
Marking 'Means to add multiple copies of the Lego Art sets to the counts' as done since this is already possible by mixing in the same set multiple times.

**Comment by debkbanerji** [comment]
Closing items referring to more flexible Bricklink export options since that functionality is in latest version.

**Comment by debkbanerji** [comment]
Closed color name item - added in tooltip in latest version

**Comment by debkbanerji** [comment]
Closed image in instructions item since that is in latest version

**Comment by debkbanerji** [comment]
Closed color name in instructions item since that is in latest version

**Comment by debkbanerji** [comment]
Closing remaining issues for now. The counts needed for each color can be determined by maximizing the cap and seeing which studs are actually used. The color palette contains all the bricklink solid colors for which the pixel pieces exist. Non solid colors (transparent, metallic, etc.) have deliberately been left out since those aren't represented well in code/input images. As for filename in the result, if you mean the name of the generated pdf, it can be set at download time based on the user's browser settings.
