### ISSUE TITLE
Cropping/other formats

### ISSUE THREAD

**Issue by Wind2dk** [debkbanerji/lego-art-remix#11]
Awesome work! AWESOME!

Would it be possible to add more formats such as 4:3 images or cropping the final image in some way (So it's changed in the pdf)?

**Comment by debkbanerji** [comment]
More resolutions and aspect ratios can be selected in the step 1 slider, such as 4:3. Cropping could be added, but is a little tedious to implement since it would clutter the UI. You can still crop the image before adding it to the tool, and it will have the same effect. Closing this issue for now since there is a workaround.
