### ISSUE TITLE
[Bug] Surprised by colour matching

### ISSUE THREAD

**Issue by hansdemol** [debkbanerji/lego-art-remix#111]
**Bug Description**

First of all: I am a GREAT fan of this tool!

And then my question (not sure it is a bug...)

I am surprised by the colors that are chosen in the conversion (when using 'all tile colors'):
For example: I have filled 4 large areas using the Rebrickable values for Bright Green, Bright Light Orange, Coral and Yellow
(just as an example).

Both Bright Green and Coral get 'converted' in the expected colors.

But my 'Bright Light Orange' zone is converted into 'Yellow'.
My 'Yellow' is converted into 'Neon Yellow'

(I did not change anything in the default values of step2, 3 and 4)

In this case I would expect a 1 to 1 conversion, no?

This is the picture I used (fields filled with the rebrickable color codes)

![Screenshot 2023-09-30 000838](https://github.com/debkbanerji/lego-art-remix/assets/146491926/3dc46387-757a-4548-aa07-fb0ac8a4f03d)

My main question is: which HEX or RGB colors to use to get a guaranteed 1 to 1 conversion?

Thanks for looking into this!

Hans

**Comment by debkbanerji** [comment]
Hi Hans,

Thanks for opening the issue! Dealing with color is a bit tricky, since there are a few different ways of classifying Lego colors, which map from real world to hex colors in different ways, and assign them different names (so Rebrickable, Bricklink, and official Lego colors may be different). The source of truth for what Lego Art Remix uses for color definitions can be found here: https://github.com/debkbanerji/lego-art-remix/blob/master/app/js/bricklink-colors.js so you can check against this file to verify what hex color is being compared against at runtime.

There is one other factor at play. When using round tiles/plates the black from the base plates bleeds through and makes the image appear darker. Lego Art Remix corrects for this darkening, so even if the input image hex code matches an existing color, that color may not be chosen, since that would make the image appear darker than it should be. If you want to see what is different when this correction is not applied, you can choose the square plate/tile pixel type and Lego Art Remix will not color correct (since the underlying base plate would not be visible if the pixels are tiles).

Let me know if something still seems off!

**Comment by hansdemol** [comment]
Hi Deb,

Thank you very much for your reply - I appreciate that!

And I find the part about the 'correction' very interesting. Well seen!
Thank you very much for the link with the colors! VERY useful :)

I will run some more tests and keep you posted.

But: you gave a TOP reply!

Hans

**Comment by hansdemol** [comment]
Hi Deb,

Can you just tell me where I can switch from 'round' to 'square'?

I just did a test with 'Lots of Dots - Square Tiles only' and the result remained the same (still displaying round pieces and colors remained the same).

Thanks for a small additional answer ;)

Hans

**Comment by debkbanerji** [comment]
The 'Pixel Piece' option in step 3 determines if round or square is used. When you select a different value in this dropdown, the pictures that show up in step 3 and 4 should change accordingly.

**Comment by hansdemol** [comment]
YES!  All is clear now to me!
Thanks for your help!!
Really appreciated!
