### ISSUE TITLE
Changing the section size?

### ISSUE THREAD

**Issue by shwekwek** [debkbanerji/lego-art-remix#12]
Beautiful, amazing Job! well done.
I think there is a lot of potential for this app to be used by 3d printing nerds (just like me...)
I want to offer to allow adjusting the size of the board, since we can detrmine what board size to print. for example, i preffer to print 24X24 boards, and then use only 4 pieces instead of 6. the only problem is that the PDF instuction outcome won't fit and be quite confusing to follow. Just a thought.
In addition - instead of giving option to crop the image - i would advise to automaticaly change the ratio of the outcome to fit the original image.
Thats all, thanks for your amazing work.

**Comment by debkbanerji** [comment]
This is a really good quality of life feature but a tricky one since it messes up the pdf generation logic - I'm leaving this open for now in case I get the chance to do it but there's no guarantee I'll have time to get to this one.

**Comment by debkbanerji** [comment]
This functionality is now available with the understanding that because of the way the instruction pdf is generated, this feature won't work correctly for more granular resolutions. You can access the more granular resolution option by adding a url parameter: [https://lego-art-remix.debkbanerji.com/?forceUnsupportedDimensions](https://lego-art-remix.debkbanerji.com/?forceUnsupportedDimensions)

Cropping isn't supported in the first place, but resizing is - it's not possible to automatically preserve the original resolution and aspect ratio in most cases since the dimensions are required to be multiples of 16 and need to be limited for performance/practicality, assuming `forceUnsupportedDimensions` isn't enabled.
