### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by DutchHoodedOne** [debkbanerji/lego-art-remix#23]
Hi,

Love this site, but ran into a small problem.
When trying a very large mosaic (160 x 160), the instructions part-5, do not get downloaded. Part-6 is only the last plate. And the rest works perfect.

thnx in advance.

**Comment by debkbanerji** [comment]
Thanks for filing the task! - I haven't been able to reproduce this in prod (tried with both low and high quality options). Would it be possible for you to share the console logs/a video of the issue? (you can access this through the inspect element functionality of most browsers). Depending on your browser, it is possible that the downloads are triggered at different times due to a race condition, so it is also possible (though unlikely) that part 5 is downloaded after part 6.

**Comment by DutchHoodedOne** [comment]
Hi,

I’ll see what I can do. I’m not very technical with these things. i just expect them to work. Btw, I’m using Safari, and maybe I just need to use a different browser. Safari has been doing more weird stuff lately. 
It seems to happen only when at least one side is 160 long.

Cheers,
Hans

**Comment by DutchHoodedOne** [comment]
Hi,

Same computer, different browser, no problems....

**Comment by debkbanerji** [comment]
Browser specific issue, it seems - please reopen if this continues to be a problem (workarounds seem to be sufficient for now)
