### ISSUE TITLE
Piece count 

### ISSUE THREAD

**Issue by Betzweaverbird** [debkbanerji/lego-art-remix#76]
**Is your feature request related to a problem? If so, please describe it.**
A description of what the problem is. Ex. I'm always frustrated when [...] please make it so i can input the number studs I want to use and configures the image to fit the panel by amount of studs. For instance I have the art project set I would like to use one panel for a symbol instead of all the panels.

**Describe the solution you'd like**
A description of what you want to happen or what the feature would look like when implemented.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by debkbanerji** [comment]
The formatting for this issue is a little weird, which makes things a little tricky to read. I'm not quite sure what's being requested here, but the ability to choose both resolution and number of pieces already exists.

Closing this for now - lmk if there are more specifics about what's being asked for here.

**Comment by Betzweaverbird** [comment]
I guess I just don’t understand how to work with this app
