### ISSUE TITLE
Yet ANOTHER new flesh color - "Warm Tan" or "Medium Tan" for 2022

### ISSUE THREAD

**Issue by douglasblash** [debkbanerji/lego-art-remix#94]
Hey deb,

Just as a heads up, they've introduced yet ANOTHER new flesh-tone to the lineup this year.  

It's a lighter one, and it's called "Warm Tan" by Lego and ReBrickable, and it's called "Medium Tan" on BrickLink.  I don't think any of the hex codes I've seen are 100% accurate, since ReBrickable shows it as too dark, and BrickLink is showing it as way too cool.  But it's essentially an exact mid-point between "Light Nougat" and "Nougat", so you could just interpolate it's RGB values for now.  

All together, also including the recent addition of "Medium Brown", it looks like that completes their full intended lineup of flesh-tones.  If you look at the review of minifigs in the new Foosball Table set on Brickset, it clarifies everything...

[https://brickset.com/article/83994/a-look-at-the-minifigs-in-21337-table-football](url)

Naturally, there are no tiles just yet, but the color officially exists, so it should be added to "All Existing Colors" with a hex code.

Great Work, Thanks!  =)

**Comment by debkbanerji** [comment]
Thanks for calling this out - just added this in based on Bricklink's color list and it's available in v2022.10.22. If their hex code does change, or it gets added to some sets lmk and I can add it in (unless I realize it on my own first lol)

On a side note, maybe I should just bite the bullet and write a script to directly pull the color info and set availability from bricklink rather than having to do this manually each time, but I need to find the time to do it.
